//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPhamWeb.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int id { get; set; }
        public string name { get; set; }
        public string img { get; set; }
        public string description { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<int> count { get; set; }
        public Nullable<double> pricefordistributors { get; set; }
    }
}
